project_id = "bessucubulzbrrujkcxg"

[functions.agentbuddy-oauth]
verify_jwt = false

[functions.agentbuddy-sync]
verify_jwt = false

[functions.agentbuddy-add-note]
verify_jwt = true

[functions.send-campaign]
verify_jwt = true

[functions.resend-webhook]
verify_jwt = false

[functions.auth-email]
verify_jwt = false

[functions.find-nearby-sales]
verify_jwt = true
